### PR TITLE
Don't use `--show-current` for getting branch

### LINKED ISSUE #1: Don't use --show-current
It's a more recent feature in git so not available in all environments,  I updated my local git installation and it works. But it's failing in my CI pipeline because the docker image I'm using has an older version of git (official node:10, which is not that old).

Would be better to use:

`git rev-parse --abbrev-ref HEAD`

as it's more likely to work everywhere.

### PR DESCRIPTION
**Pull request by AbhyudayaSharma**
Closes #1

### CODE REVIEW

**Comment by rohit-gohri** [comment]
Thanks for the quick fix! Can this be released? Only thing stopping me from adding it to my project.

**Comment by AbhyudayaSharma** [comment]
@rohit-gohri I'll do a release today.

**Comment by AbhyudayaSharma** [comment]
@rohit-gohri https://github.com/AbhyudayaSharma/react-git-info/releases/tag/v1.0.1

**Comment by rohit-gohri** [comment]
> @rohit-gohri [`v1.0.1` (release)](https://github.com/AbhyudayaSharma/react-git-info/releases/tag/v1.0.1)

Great! Thanks!

**Pull request merged**
